---
title: "index"
author: "Aleksander Partyga"
date: "8 06 2022"
output: html_document
---

```{r setup, include = FALSE}
library(ggplot2)
library(dplyr)
library(ggthemes)
library(gridExtra)
library(grid)
devtools::install_github("rensa/ggflags")
library(ggflags)
devtools::install_github("zeehio/facetscales")
library(facetscales)


knitr::opts_chunk$set(echo = FALSE, message = FALSE)
options(scipen = 999)
```


```{r, include = FALSE}
atp <- read.csv("C:/Users/lenovo/Desktop/WNE/Advanced Visualisation R/Project/ATP.csv")

atp <- transform(atp, tourney_date = as.Date(as.character(tourney_date), "%Y%m%d"))

atp_XXI <- atp[atp$tourney_date >= "2000-01-01",]

# Filtering for Djokovic, Nadal and Federer matches only
DNF_matches <- atp_XXI %>%
  filter(loser_id %in% c(104925, 104745, 103819) | winner_id %in% c(104925, 104745, 103819))

### Roger Federer matches won on each surface ###

RF <- DNF_matches %>%
  filter((loser_id == 103819 | winner_id == 103819) & surface %in% c("Clay", "Grass", "Hard"))

RF <- RF %>%
  select(winner_name, winner_rank, loser_name, loser_rank, surface)

RF$is_winner <- ifelse(RF$winner_name == 'Roger Federer', T, F)

RF_stats <- as.data.frame(table(RF$is_winner, RF$surface))
names(RF_stats) <- c("Won", "Surface", "Freq")

RF_stats <- RF_stats %>%
  group_by(Surface) %>%
  mutate(Percent = paste0(round(Freq*100 / sum(Freq)), "%"))

RF_plot <- 
  ggplot(RF_stats, aes(x = Surface, y = Freq, fill = Won)) +
    geom_bar(stat = 'identity', color = 'black', show.legend = F) +
    geom_text(aes(label = Percent), position = position_stack(vjust = 0.5), size = 3.5) +
    scale_fill_manual(values = c("#de7662", "#86cf70")) +
    scale_y_continuous(breaks = seq(0, 1000, by = 100),
                       limits = c(0, 900)) +
    labs(x = "", y = "", title = "Roger Federer") +
    theme_gray() +
    theme(plot.title = element_text(hjust = 0.5))


RF_plot + theme(plot.title = element_text(size = 20, face = "bold"),
                plot.subtitle = element_text(size = 15),
                axis.text.x = element_text(size = 12),
                axis.title.y = element_text(size = 12, margin = margin(r = 10)))

### Novak Djokovic matches won on each surface ###

ND <- DNF_matches %>%
  filter((loser_id == 104925 | winner_id == 104925) & surface %in% c("Clay", "Grass", "Hard"))

ND <- ND %>%
  select(winner_name, surface)

ND$is_winner <- ifelse(ND$winner_name == 'Novak Djokovic', T, F)

ND_stats <- as.data.frame(table(ND$is_winner, ND$surface))
names(ND_stats) <- c("Won", "Surface", "Freq")

ND_stats <- ND_stats %>%
  group_by(Surface) %>%
  mutate(Percent = paste0(round(Freq*100 / sum(Freq)), "%"))

ND_plot <- 
  ggplot(ND_stats, aes(x = Surface, y = Freq, fill = Won)) +
  geom_bar(stat = 'identity', color = 'black', show.legend = F) +
  geom_text(aes(label = Percent), position = position_stack(vjust = 0.5), size = 3.5) +
  scale_fill_manual(values = c("#de7662", "#86cf70")) +
  scale_y_continuous(breaks = seq(0, 1000, by = 100),
                     limits = c(0, 900)) +
  labs(x = "", y = "", title = "Novak Djokovic") +
  theme_gray() +
  theme(plot.title = element_text(hjust = 0.5))


### Rafael Nadal matches won on each surface ###

RN <- DNF_matches %>%
  filter((loser_id == 104745 | winner_id == 104745) & surface %in% c("Clay", "Grass", "Hard"))

RN <- RN %>%
  select(winner_name, surface)

RN$is_winner <- ifelse(RN$winner_name == 'Rafael Nadal', T, F)

RN_stats <- as.data.frame(table(RN$is_winner, RN$surface))
names(RN_stats) <- c("Won", "Surface", "Freq")

RN_stats <- RN_stats %>%
  group_by(Surface) %>%
  mutate(Percent = paste0(round(Freq*100 / sum(Freq)), "%"))

RN_plot <- 
  ggplot(RN_stats, aes(x = Surface, y = Freq, fill = Won)) +
  geom_bar(stat = 'identity', color = 'black', show.legend = F) +
  geom_text(aes(label = Percent), position = position_stack(vjust = 0.5), size = 3.5) +
  scale_fill_manual(values = c("#de7662", "#86cf70")) +
  scale_y_continuous(breaks = seq(0, 1000, by = 100),
                     limits = c(0, 900)) +
  labs(y = "", x = "", title = "Rafael Nadal") +
  theme_gray() +
  theme(plot.title = element_text(hjust = 0.5))
```


```{r}
grid.arrange(RF_plot, ND_plot, RN_plot, ncol = 3, 
             top = textGrob("Big Three performance on different surfaces in years 2000 - 2018",
             gp = gpar(fontsize = 16, vjust = 2, col = "#3335a1", face = "bold")),
             left = "Number of matches played (wins in green)", bottom = textGrob("Surface",
             gp = gpar(fontsize = 12)))
```


